version: '3.8'

services:
  todo-postgres:
    image: postgres:15
    container_name: todo-postgres
    environment:
      POSTGRES_DB: tododb
      POSTGRES_USER: todouser
      POSTGRES_PASSWORD: todopass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U todouser -d tododb"]
      interval: 10s
      timeout: 5s
      retries: 5

  todo-rest-service:
    image: henry170/todo-rest:latest
    container_name: todo-rest-service
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://todo-postgres:5432/tododb
      QUARKUS_DATASOURCE_USERNAME: todouser
      QUARKUS_DATASOURCE_PASSWORD: todopass
    ports:
      - "8080:8080"
    depends_on:
      todo-postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/q/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  todo-web-service:
    image: henry170/todo-web:latest
    container_name: todo-web-service
    environment:
      TODO_REST_URL: http://todo-rest-service:8080
    ports:
      - "8081:8081"
    depends_on:
      - todo-rest-service

  todo-gateway:
    image: nginx:alpine
    container_name: todo-gateway
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - todo-rest-service
      - todo-web-service

  todo-prometheus:
    image: prom/prometheus:latest
    container_name: todo-prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    depends_on:
      - todo-rest-service

  todo-grafana:
    image: grafana/grafana:latest
    container_name: todo-grafana
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  postgres_data:
  grafana_data:
